// swift-tools-version:5.3
import PackageDescription

let package = Package(
    name: "ReactiveObjC",
    platforms: [
        .iOS(.v12),
        .macOS(.v10_15),
        .watchOS(.v2),
        .tvOS(.v9)
    ],
    products: [
        .library(
            name: "ReactiveObjC",
            targets: ["ReactiveObjC"]
        )
    ],
    targets: [
                .target(
            name: "ReactiveObjC",
            path: "ReactiveObjC",
            sources: [
"EXTRuntimeExtensions.m",
"NSArray+RACSequenceAdditions.m",
"NSData+RACSupport.m",
"NSDictionary+RACSequenceAdditions.m",
"NSEnumerator+RACSequenceAdditions.m",
"NSIndexSet+RACSequenceAdditions.m",
"NSInvocation+RACTypeParsing.m",
"NSNotificationCenter+RACSupport.m",
"NSObject+RACDeallocating.m",
"NSObject+RACDescription.m",
"NSObject+RACKVOWrapper.m",
"NSObject+RACLifting.m",
"NSObject+RACPropertySubscribing.m",
"NSObject+RACSelectorSignal.m",
"NSOrderedSet+RACSequenceAdditions.m",
"NSSet+RACSequenceAdditions.m",
"NSString+RACKeyPathUtilities.m",
"NSString+RACSequenceAdditions.m",
"NSString+RACSupport.m",
"NSURLConnection+RACSupport.m",
"NSUserDefaults+RACSupport.m",
"RACArraySequence.m",
"RACBehaviorSubject.m",
"RACBlockTrampoline.m",
"RACChannel.m",
"RACCommand.m",
"RACCompoundDisposable.m",
"RACDelegateProxy.m",
"RACDisposable.m",
"RACDynamicSequence.m",
"RACDynamicSignal.m",
"RACEagerSequence.m",
"RACEmptySequence.m",
"RACEmptySignal.m",
"RACErrorSignal.m",
"RACEvent.m",
"RACGroupedSignal.m",
"RACImmediateScheduler.m",
"RACIndexSetSequence.m",
"RACKVOChannel.m",
"RACKVOProxy.m",
"RACKVOTrampoline.m",
"RACMulticastConnection.m",
"RACPassthroughSubscriber.m",
"RACQueueScheduler.m",
"RACReplaySubject.m",
"RACReturnSignal.m",
"RACScheduler.m",
"RACScopedDisposable.m",
"RACSequence.m",
"RACSerialDisposable.m",
"RACSignal+Operations.m",
"RACSignal.m",
"RACSignalSequence.m",
"RACStream.m",
"RACStringSequence.m",
"RACSubject.m",
"RACSubscriber.m",
"RACSubscriptingAssignmentTrampoline.m",
"RACSubscriptionScheduler.m",
"RACTargetQueueScheduler.m",
"RACTestScheduler.m",
"RACTuple.m",
"RACTupleSequence.m",
"RACUnarySequence.m",
"RACUnit.m",
"RACValueTransformer.m",
// "MKAnnotationView+RACSignalSupport.m",
// "NSControl+RACCommandSupport.m",
// "NSControl+RACTextSignalSupport.m",
// "NSFileHandle+RACSupport.m",
// "NSObject+RACAppKitBindings.m",
// "NSText+RACSignalSupport.m",
"UIActionSheet+RACSignalSupport.m",
"UIAlertView+RACSignalSupport.m",
"UIBarButtonItem+RACCommandSupport.m",
"UIButton+RACCommandSupport.m",
"UICollectionReusableView+RACSignalSupport.m",
"UIControl+RACSignalSupport.m",
"UIControl+RACSignalSupportPrivate.m",
"UIDatePicker+RACSignalSupport.m",
"UIGestureRecognizer+RACSignalSupport.m",
"UIImagePickerController+RACSignalSupport.m",
"UIRefreshControl+RACCommandSupport.m",
"UISegmentedControl+RACSignalSupport.m",
"UISlider+RACSignalSupport.m",
"UIStepper+RACSignalSupport.m",
"UISwitch+RACSignalSupport.m",
"UITableViewCell+RACSignalSupport.m",
"UITableViewHeaderFooterView+RACSignalSupport.m",
"UITextField+RACSignalSupport.m",
"UITextView+RACSignalSupport.m",

            ],
            publicHeadersPath: "include",
            cSettings: [
                .headerSearchPath("include/ReactiveObjC"),
                .define("SWIFTPM", to: "1") 
            ]
        )

    ],
    swiftLanguageVersions: [.v5]
)
